/**
 * Higgsfield's catalogue — generated, not hand-written.
 *
 * Each entry is one documented workflow: its exact endpoint path and the exact
 * wire names, types, enums and bounds of its request body, taken from the
 * schema Higgsfield publishes for that workflow.
 *
 * Field names matter more here than anywhere else in this codebase. The API
 * ignores keys it does not recognise, so a misspelled parameter is not
 * rejected — it is silently dropped, and the generation is billed anyway.
 *
 * Regenerate with `npm run sync:higgsfield`. Do not edit by hand.
 *
 * Source: https://docs.higgsfield.ai/docs/models
 * Synced: 2026-09-23 — 82 workflows
 */

export type HiggsfieldFieldType = 'string' | 'integer' | 'number' | 'boolean' | 'array' | 'object'

export interface HiggsfieldField {
  /** The wire name, sent verbatim. */
  name: string
  type: HiggsfieldFieldType
  required?: boolean
  default?: string | number | boolean
  enum?: (string | number)[]
  min?: number
  max?: number
  step?: number
  minItems?: number
  maxItems?: number
  format?: string
  itemFormat?: string
  /** Set when the field takes a URL to media the caller has to supply. */
  media?: 'image' | 'video' | 'audio'
}

export interface HiggsfieldWorkflow {
  /** `family/workflow` — the model id KOVAI uses everywhere else. */
  id: string
  /** Path appended to the API base, exactly as documented. */
  endpoint: string
  family: string
  familyName: string
  workflow: string
  description: string
  output: 'image' | 'video'
  fields: HiggsfieldField[]
}

export const HIGGSFIELD_WORKFLOWS: HiggsfieldWorkflow[] = [
  {
    id: "grok-image-2/generate-and-edit",
    endpoint: "/xai/grok-imagine-image-2.0",
    family: "grok-image-2",
    familyName: "Grok Image 2.0",
    workflow: "Generate and edit",
    description: "Generate and edit with Grok Image 2.0: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "quality",
        type: "string",
        enum: ["low", "medium"],
        default: "medium",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 10,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "1:1", "1:2", "2:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16"],
        default: "auto",
      },
    ],
  },
  {
    id: "ideogram-4/generate",
    endpoint: "/ideogram/v4.0",
    family: "ideogram-4",
    familyName: "Ideogram 4.0",
    workflow: "Generate",
    description: "Generate with Ideogram 4.0: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "1:2", "2:1", "2:3", "3:2", "4:5", "5:4", "9:16", "16:9", "5:8", "8:5", "3:4", "4:3", "9:22", "22:9", "9:23", "23:9", "3:8", "8:3", "5:12", "12:5", "1:3", "3:1"],
        default: "1:1",
      },
      {
        name: "image_weight",
        type: "integer",
        min: 1,
        max: 100,
      },
      {
        name: "rendering_speed",
        type: "string",
        enum: ["TURBO", "DEFAULT", "QUALITY"],
        default: "DEFAULT",
      },
    ],
  },
  {
    id: "marketing-studio-image/generate-and-edit",
    endpoint: "/marketing-studio/image",
    family: "marketing-studio-image",
    familyName: "Marketing Studio Image",
    workflow: "2.0 Alpha",
    description: "2.0 Alpha with Marketing Studio Image: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "quality",
        type: "string",
        enum: ["low", "medium", "high"],
        default: "high",
      },
      {
        name: "preset_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 16,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "moderation",
        type: "string",
        enum: ["auto", "low"],
        default: "auto",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k", "4k"],
        default: "2k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9"],
        default: "auto",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "marketing-studio-image/flare",
    endpoint: "/marketing-studio/image/flare",
    family: "marketing-studio-image",
    familyName: "Marketing Studio Image",
    workflow: "2.5 Flare",
    description: "2.5 Flare with Marketing Studio Image: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "quality",
        type: "string",
        enum: ["low", "medium", "high", "xhigh", "max"],
        default: "high",
      },
      {
        name: "preset_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 16,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "moderation",
        type: "string",
        enum: ["auto", "low"],
        default: "auto",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k", "4k"],
        default: "2k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9"],
        default: "auto",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "marketing-studio-image/sunburst",
    endpoint: "/marketing-studio/image/sunburst",
    family: "marketing-studio-image",
    familyName: "Marketing Studio Image",
    workflow: "2.5 Sunburst",
    description: "2.5 Sunburst with Marketing Studio Image: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "quality",
        type: "string",
        enum: ["low", "medium", "high", "xhigh", "max"],
        default: "high",
      },
      {
        name: "preset_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 16,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "moderation",
        type: "string",
        enum: ["auto", "low"],
        default: "auto",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k", "4k"],
        default: "2k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9"],
        default: "auto",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "qwen-image-3/edit",
    endpoint: "/alibaba/qwen-image-3/edit",
    family: "qwen-image-3",
    familyName: "Qwen Image 3",
    workflow: "Edit images",
    description: "Edit images with Qwen Image 3: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "image_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 3,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:3", "3:2", "3:4", "4:3", "7:9", "9:7", "9:16", "16:9", "21:9"],
        default: "1:1",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: true,
      },
      {
        name: "negative_prompt",
        type: "string",
      },
      {
        name: "prompt_extend_mode",
        type: "string",
        enum: ["direct"],
        default: "direct",
      },
    ],
  },
  {
    id: "qwen-image-3/text-to-image",
    endpoint: "/alibaba/qwen-image-3/text-to-image",
    family: "qwen-image-3",
    familyName: "Qwen Image 3",
    workflow: "Text to image",
    description: "Text to image with Qwen Image 3: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:3", "3:2", "3:4", "4:3", "7:9", "9:7", "9:16", "16:9", "21:9"],
        default: "1:1",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: true,
      },
      {
        name: "negative_prompt",
        type: "string",
      },
      {
        name: "prompt_extend_mode",
        type: "string",
        enum: ["direct", "agent"],
        default: "direct",
      },
    ],
  },
  {
    id: "recraft-v4-1/text-to-image",
    endpoint: "/recraft/v4.1/text-to-image",
    family: "recraft-v4-1",
    familyName: "Recraft V4.1",
    workflow: "Text to image",
    description: "Text to image with Recraft V4.1: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "colors",
        type: "array",
        maxItems: 10,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:1", "1:2", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "6:10", "14:10", "10:14", "16:9", "9:16"],
        default: "1:1",
      },
      {
        name: "output_format",
        type: "string",
        enum: ["jpg", "png", "webp"],
        default: "jpg",
      },
      {
        name: "background_color",
        type: "object",
      },
    ],
  },
  {
    id: "recraft-v4-1-pro/generate",
    endpoint: "/recraft/v4.1/pro/text-to-image",
    family: "recraft-v4-1-pro",
    familyName: "Recraft V4.1 Pro",
    workflow: "Text to image",
    description: "Text to image with Recraft V4.1 Pro: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "colors",
        type: "array",
        maxItems: 10,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["2k"],
        default: "2k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:1", "1:2", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "6:10", "14:10", "10:14", "16:9", "9:16"],
        default: "1:1",
      },
      {
        name: "output_format",
        type: "string",
        enum: ["jpg", "png", "webp"],
        default: "jpg",
      },
      {
        name: "background_color",
        type: "object",
      },
    ],
  },
  {
    id: "recraft-v4-1-utility/text-to-image",
    endpoint: "/recraft/v4.1/utility/text-to-image",
    family: "recraft-v4-1-utility",
    familyName: "Recraft V4.1 Utility",
    workflow: "Text to image",
    description: "Text to image with Recraft V4.1 Utility: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "colors",
        type: "array",
        maxItems: 10,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:1", "1:2", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "6:10", "14:10", "10:14", "16:9", "9:16"],
        default: "1:1",
      },
      {
        name: "output_format",
        type: "string",
        enum: ["jpg", "png", "webp"],
        default: "jpg",
      },
      {
        name: "background_color",
        type: "object",
      },
    ],
  },
  {
    id: "recraft-v4-1-utility-pro/text-to-image",
    endpoint: "/recraft/v4.1/utility/pro/text-to-image",
    family: "recraft-v4-1-utility-pro",
    familyName: "Recraft V4.1 Utility Pro",
    workflow: "Text to image",
    description: "Text to image with Recraft V4.1 Utility Pro: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "colors",
        type: "array",
        maxItems: 10,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["2k"],
        default: "2k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:1", "1:2", "3:2", "2:3", "4:3", "3:4", "5:4", "4:5", "6:10", "14:10", "10:14", "16:9", "9:16"],
        default: "1:1",
      },
      {
        name: "output_format",
        type: "string",
        enum: ["jpg", "png", "webp"],
        default: "jpg",
      },
      {
        name: "background_color",
        type: "object",
      },
    ],
  },
  {
    id: "soul-standard/generate",
    endpoint: "/higgsfield-ai/soul/standard",
    family: "soul-standard",
    familyName: "SOUL",
    workflow: "Text to image",
    description: "Text to image with SOUL: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["9:16", "16:9", "4:3", "3:4", "1:1", "2:3", "3:2"],
        default: "4:3",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
      {
        name: "style_id",
        type: "string",
        default: "464ea177-8d40-4940-8d9d-b438bab269c7",
        format: "uuid",
      },
      {
        name: "style_strength",
        type: "number",
        default: 1,
        min: 0,
        max: 1,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 1000000,
      },
      {
        name: "custom_reference_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "custom_reference_strength",
        type: "number",
        default: 1,
        min: 0,
        max: 1,
      },
      {
        name: "image_reference_url",
        type: "string",
        format: "uri",
      },
      {
        name: "batch_size",
        type: "integer",
        enum: [1, 4],
        default: 1,
      },
    ],
  },
  {
    id: "soul-cinema/generate",
    endpoint: "/higgsfield-ai/soul/cinema",
    family: "soul-cinema",
    familyName: "SOUL Cinema",
    workflow: "Text to image",
    description: "Text to image with SOUL Cinema: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["9:16", "16:9", "4:3", "3:4", "1:1", "2:3", "3:2"],
        default: "1:1",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "custom_reference_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "custom_reference_strength",
        type: "number",
        default: 1,
        min: 0,
        max: 1,
      },
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 1000000,
      },
      {
        name: "batch_size",
        type: "integer",
        enum: [1, 4],
        default: 1,
      },
    ],
  },
  {
    id: "soul-id/create-character",
    endpoint: "/v1/custom-references",
    family: "soul-id",
    familyName: "Soul ID",
    workflow: "Create character",
    description: "Create character with Soul ID: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "name",
        type: "string",
        required: true,
      },
      {
        name: "model_version",
        type: "string",
        default: "v1",
      },
      {
        name: "input_images",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 100,
      },
    ],
  },
  {
    id: "soul-2/generate",
    endpoint: "/higgsfield-ai/soul/v2/standard",
    family: "soul-2",
    familyName: "SOUL V2",
    workflow: "Text to image",
    description: "Text to image with SOUL V2: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["9:16", "16:9", "4:3", "3:4", "1:1", "2:3", "3:2"],
        default: "1:1",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "enhance_prompt",
        type: "boolean",
        default: false,
      },
      {
        name: "custom_reference_id",
        type: "string",
        format: "uuid",
      },
      {
        name: "custom_reference_strength",
        type: "number",
        default: 1,
        min: 0,
        max: 1,
      },
      {
        name: "style_id",
        type: "string",
        default: "3db34ab5-3439-4317-9e03-08dc30852e69",
        format: "uuid",
      },
      {
        name: "style_strength",
        type: "number",
        default: 1,
        min: 0,
        max: 1,
      },
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 1000000,
      },
      {
        name: "batch_size",
        type: "integer",
        enum: [1, 4],
        default: 1,
      },
    ],
  },
  {
    id: "z-image-turbo/generate",
    endpoint: "/z-image/turbo",
    family: "z-image-turbo",
    familyName: "Z-Image Turbo",
    workflow: "Generate",
    description: "Generate with Z-Image Turbo: request parameters, examples and response handling.",
    output: "image",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["1k", "2k"],
        default: "1k",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["1:1", "2:3", "3:2", "3:4", "4:3", "7:9", "9:7", "9:16", "16:9", "21:9"],
        default: "1:1",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "cinema-studio-4/generate",
    endpoint: "/higgsfield/cinema-studio/4.0",
    family: "cinema-studio-4",
    familyName: "Cinema Studio 4.0",
    workflow: "Generate",
    description: "Generate with Cinema Studio 4.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "era",
        type: "string",
        enum: ["1960s", "1980s", "1990s", "2000s", "2020s"],
      },
      {
        name: "genre",
        type: "string",
        enum: ["epic", "drama", "noir", "comedy", "horror", "action"],
      },
      {
        name: "light",
        type: "string",
        enum: ["silhouette", "practicals", "window", "overhead-fall", "contre-jour", "soft-cross"],
      },
      {
        name: "pacing",
        type: "string",
        enum: ["chaotic", "dynamic", "calm", "single-shot"],
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 30,
      },
      {
        name: "audio_urls",
        type: "array",
        maxItems: 10,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        maxItems: 30,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        maxItems: 10,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "camera_lens",
        type: "string",
        enum: ["clean-sharp", "anamorphic", "vintage-anamorphic", "warm-vintage", "halation-vintage"],
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
        default: "16:9",
      },
      {
        name: "camera_model",
        type: "string",
        enum: ["modern", "35mm-film", "8mm-film", "dv-camcorder"],
      },
      {
        name: "color_palette",
        type: "string",
        enum: ["static-noon", "twilight-fable", "back-row-kissing-seats", "on-the-other-side-of-the-porthole", "the-emerald-ambush", "highway-standoff", "the-faded-fresco", "oil-ochre", "the-mountain-convent", "ghost-in-the-code", "pink-velvet", "two-days-to-the-horizon", "industrial-fog", "stairs-go-up", "field-post", "home-is-the-next-gas-station", "glossy-flesh", "the-crimson-ballet", "neon-rain-at-midnight", "the-morning-after-rain", "the-iron-borough", "the-ground", "the-investigation", "turquoise-mirage", "a-dream-in-color", "breakfast-on-schedule", "favela-gold", "a-hotel-for-one", "after-dark", "crimson-vigi", "the-neighbors-saw-everything", "the-grey-channel", "mirage-at-noon", "bubblegum-boulevard", "yellow-room", "the-earth-keeps-things-reluctantly", "tropic-fever-dream", "bioluminescent-night", "dont-turn-it-off-im-watching", "the-silk-curtain-falls", "the-butterfly", "playtime", "wallpaper-romance", "overtime", "the-way-home-is-longer", "everyone-speaks-in-whispers", "runaway-summer", "amber-wasteland", "the-circus", "gasoline-sunset"],
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "camera_aperture",
        type: "string",
        enum: ["f14-wide-open", "f4-moderate", "f11-deep-focus"],
      },
      {
        name: "camera_movement",
        type: "string",
        enum: ["snorricam", "robot-arm", "tilt-up", "rack-focus", "tilt-down", "pov", "pan-left", "crane-up", "pan-right", "crane-down", "side-tracking", "pedestal-up", "pedestal-down", "handheld", "tracking", "drone-orbit", "dolly-zoom", "aerial-pullback", "static-shot", "bullet-time", "whip-pan", "slow-zoom-in", "arc-left", "slow-zoom-out", "arc-right", "truck-right", "dolly-in", "truck-left", "dolly-out", "slider-right", "crush-zoom", "slider-left", "helicopter-shot"],
      },
    ],
  },
  {
    id: "genjutsu/motion-transfer",
    endpoint: "/higgsfiled/genjutsu/motion-transfer/v1.0",
    family: "genjutsu",
    familyName: "Genjutsu",
    workflow: "Motion transfer",
    description: "Motion transfer with Genjutsu: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "image_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 8,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "480p"],
        default: "720p",
      },
    ],
  },
  {
    id: "genjutsu/object-swap",
    endpoint: "/higgsfiled/genjutsu/object-swap/v1.0",
    family: "genjutsu",
    familyName: "Genjutsu",
    workflow: "Object swap",
    description: "Object swap with Genjutsu: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "image_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 8,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "480p"],
        default: "720p",
      },
    ],
  },
  {
    id: "grok-video-1-5/reference-to-video",
    endpoint: "/xai/grok-imagine-video/v1.5/reference-to-video",
    family: "grok-video-1-5",
    familyName: "Grok Imagine Video 1.5",
    workflow: "Reference to video",
    description: "Reference to video with Grok Imagine Video 1.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 1,
        max: 15,
      },
      {
        name: "audio_url",
        type: "string",
        format: "uri",
        media: "audio",
      },
      {
        name: "image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 7,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "480p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"],
        default: "auto",
      },
    ],
  },
  {
    id: "hailuo-2-3/standard-image-to-video",
    endpoint: "/minimax/hailuo-2.3/standard/image-to-video",
    family: "hailuo-2-3",
    familyName: "Hailuo 2.3",
    workflow: "Standard image to video",
    description: "Standard image to video with Hailuo 2.3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [6, 10],
        default: 6,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "prompt_optimizer",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "hailuo-2-3/standard-text-to-video",
    endpoint: "/minimax/hailuo-2.3/standard/text-to-video",
    family: "hailuo-2-3",
    familyName: "Hailuo 2.3",
    workflow: "Standard text to video",
    description: "Standard text to video with Hailuo 2.3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [6, 10],
        default: 6,
      },
      {
        name: "prompt_optimizer",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "happy-horse-1/image-to-video",
    endpoint: "/alibaba/happy-horse/image-to-video",
    family: "happy-horse-1",
    familyName: "Happy Horse 1.0",
    workflow: "Image to video",
    description: "Image to video with Happy Horse 1.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
    ],
  },
  {
    id: "happy-horse-1/reference-to-video",
    endpoint: "/alibaba/happy-horse/reference-to-video",
    family: "happy-horse-1",
    familyName: "Happy Horse 1.0",
    workflow: "Reference to video",
    description: "Reference to video with Happy Horse 1.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "image_urls",
        type: "array",
        required: true,
        itemFormat: "uri",
        maxItems: 10,
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
    ],
  },
  {
    id: "happy-horse-1/text-to-video",
    endpoint: "/alibaba/happy-horse/text-to-video",
    family: "happy-horse-1",
    familyName: "Happy Horse 1.0",
    workflow: "Text to video",
    description: "Text to video with Happy Horse 1.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1", "4:3", "3:4"],
        default: "16:9",
      },
    ],
  },
  {
    id: "happy-horse-1-1/image-to-video",
    endpoint: "/alibaba/happy-horse/v1.1/image-to-video",
    family: "happy-horse-1-1",
    familyName: "HappyHorse 1.1",
    workflow: "Image to video",
    description: "Image to video with HappyHorse 1.1: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "1080p",
      },
    ],
  },
  {
    id: "happy-horse-1-1/reference-to-video",
    endpoint: "/alibaba/happy-horse/v1.1/reference-to-video",
    family: "happy-horse-1-1",
    familyName: "HappyHorse 1.1",
    workflow: "Reference to video",
    description: "Reference to video with HappyHorse 1.1: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "image_urls",
        type: "array",
        required: true,
        itemFormat: "uri",
        maxItems: 10,
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "1080p",
      },
    ],
  },
  {
    id: "happy-horse-1-1/text-to-video",
    endpoint: "/alibaba/happy-horse/v1.1/text-to-video",
    family: "happy-horse-1-1",
    familyName: "HappyHorse 1.1",
    workflow: "Text to video",
    description: "Text to video with HappyHorse 1.1: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "1080p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1", "4:3", "3:4"],
        default: "16:9",
      },
    ],
  },
  {
    id: "kling-2-5-turbo/pro-image-to-video",
    endpoint: "/kling-video/v2.5-turbo/pro/image-to-video",
    family: "kling-2-5-turbo",
    familyName: "Kling 2.5 Turbo",
    workflow: "Pro image to video",
    description: "Pro image to video with Kling 2.5 Turbo: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "kling-2-5-turbo/pro-text-to-video",
    endpoint: "/kling-video/v2.5-turbo/pro/text-to-video",
    family: "kling-2-5-turbo",
    familyName: "Kling 2.5 Turbo",
    workflow: "Pro text to video",
    description: "Pro text to video with Kling 2.5 Turbo: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "kling-2-5-turbo/standard-image-to-video",
    endpoint: "/kling-video/v2.5-turbo/standard/image-to-video",
    family: "kling-2-5-turbo",
    familyName: "Kling 2.5 Turbo",
    workflow: "Standard image to video",
    description: "Standard image to video with Kling 2.5 Turbo: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "kling-2-6/pro-image-to-video",
    endpoint: "/kling-video/v2.6/pro/image-to-video",
    family: "kling-2-6",
    familyName: "Kling 2.6",
    workflow: "Pro image to video",
    description: "Pro image to video with Kling 2.6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
      },
    ],
  },
  {
    id: "kling-2-6/pro-text-to-video",
    endpoint: "/kling-video/v2.6/pro/text-to-video",
    family: "kling-2-6",
    familyName: "Kling 2.6",
    workflow: "Pro text to video",
    description: "Pro text to video with Kling 2.6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
    ],
  },
  {
    id: "kling-2-6-motion-control/pro",
    endpoint: "/kling-video/motion-control/pro",
    family: "kling-2-6-motion-control",
    familyName: "Kling 2.6 Motion Control",
    workflow: "Pro",
    description: "Pro with Kling 2.6 Motion Control: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "keep_original_sound",
        type: "string",
        enum: ["yes", "no"],
        default: "yes",
      },
      {
        name: "character_orientation",
        type: "string",
        enum: ["image", "video"],
        default: "video",
      },
    ],
  },
  {
    id: "kling-2-6-motion-control/std",
    endpoint: "/kling-video/motion-control/std",
    family: "kling-2-6-motion-control",
    familyName: "Kling 2.6 Motion Control",
    workflow: "Standard",
    description: "Standard with Kling 2.6 Motion Control: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "keep_original_sound",
        type: "string",
        enum: ["yes", "no"],
        default: "yes",
      },
      {
        name: "character_orientation",
        type: "string",
        enum: ["image", "video"],
        default: "video",
      },
    ],
  },
  {
    id: "kling-3/4k-image-to-video",
    endpoint: "/kling-video/v3.0/4k/image-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "4K · Image to video",
    description: "4K · Image to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 0,
        maxItems: 6,
      },
      {
        name: "last_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-3/4k-text-to-video",
    endpoint: "/kling-video/v3.0/4k/text-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "4K · Text to video",
    description: "4K · Text to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 0,
        maxItems: 6,
      },
    ],
  },
  {
    id: "kling-3/pro-image-to-video",
    endpoint: "/kling-video/v3.0/pro/image-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Pro · Image to video",
    description: "Pro · Image to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 0,
        maxItems: 6,
      },
      {
        name: "last_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-3/pro-text-to-video",
    endpoint: "/kling-video/v3.0/pro/text-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Pro · Text to video",
    description: "Pro · Text to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 0,
        maxItems: 6,
      },
    ],
  },
  {
    id: "kling-3/standard-image-to-video",
    endpoint: "/kling-video/v3.0/std/image-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Standard · Image to video",
    description: "Standard · Image to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 1,
        maxItems: 6,
      },
      {
        name: "last_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-3/standard-text-to-video",
    endpoint: "/kling-video/v3.0/std/text-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Standard · Text to video",
    description: "Standard · Text to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "on",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "cfg_scale",
        type: "number",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 1,
        maxItems: 6,
      },
    ],
  },
  {
    id: "kling-3/turbo-image-to-video",
    endpoint: "/kling-video/v3.0-turbo/image-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Turbo · Image to video",
    description: "Turbo · Image to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
    ],
  },
  {
    id: "kling-3/turbo-text-to-video",
    endpoint: "/kling-video/v3.0-turbo/text-to-video",
    family: "kling-3",
    familyName: "Kling 3.0",
    workflow: "Turbo · Text to video",
    description: "Turbo · Text to video with Kling 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
    ],
  },
  {
    id: "kling-3-motion-control/pro",
    endpoint: "/kling-video/v3/motion-control/pro",
    family: "kling-3-motion-control",
    familyName: "Kling 3.0 Motion Control",
    workflow: "Pro",
    description: "Pro with Kling 3.0 Motion Control: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "keep_original_sound",
        type: "string",
        enum: ["yes", "no"],
        default: "yes",
      },
      {
        name: "character_orientation",
        type: "string",
        enum: ["image", "video"],
        default: "video",
      },
    ],
  },
  {
    id: "kling-3-motion-control/std",
    endpoint: "/kling-video/v3/motion-control/std",
    family: "kling-3-motion-control",
    familyName: "Kling 3.0 Motion Control",
    workflow: "Standard",
    description: "Standard with Kling 3.0 Motion Control: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        default: "",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "keep_original_sound",
        type: "string",
        enum: ["yes", "no"],
        default: "yes",
      },
      {
        name: "character_orientation",
        type: "string",
        enum: ["image", "video"],
        default: "video",
      },
    ],
  },
  {
    id: "kling-o3/first-last-frame",
    endpoint: "/kling-video/o3/first-last-frame",
    family: "kling-o3",
    familyName: "Kling O3",
    workflow: "First last frame",
    description: "First last frame with Kling O3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro", "4k"],
        default: "pro",
      },
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "off",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 1,
        maxItems: 6,
      },
      {
        name: "last_frame_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "first_frame_url",
        type: "string",
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-o3/image-reference",
    endpoint: "/kling-video/o3/image-reference",
    family: "kling-o3",
    familyName: "Kling O3",
    workflow: "Image reference",
    description: "Image reference with Kling O3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro", "4k"],
        default: "std",
      },
      {
        name: "sound",
        type: "string",
        enum: ["on", "off"],
        default: "off",
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 15,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "shot_type",
        type: "string",
        enum: ["customize", "intelligent"],
        default: "customize",
      },
      {
        name: "image_urls",
        type: "array",
        itemFormat: "uri",
        maxItems: 10,
        media: "image",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
      },
      {
        name: "multi_prompt",
        type: "array",
        minItems: 1,
        maxItems: 6,
      },
      {
        name: "last_frame_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "first_frame_url",
        type: "string",
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-o3/video-edit",
    endpoint: "/kling-video/o3/video-edit",
    family: "kling-o3",
    familyName: "Kling O3",
    workflow: "Video edit",
    description: "Video edit with Kling O3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro", "4k"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "elements",
        type: "array",
        minItems: 0,
        maxItems: 4,
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 4,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "video_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 1,
        itemFormat: "uri",
        media: "video",
      },
    ],
  },
  {
    id: "kling-o3/video-reference",
    endpoint: "/kling-video/o3/video-reference",
    family: "kling-o3",
    familyName: "Kling O3",
    workflow: "Video reference",
    description: "Video reference with Kling O3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 10,
      },
      {
        name: "elements",
        type: "array",
        minItems: 0,
        maxItems: 4,
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 4,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "video_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 1,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
      },
    ],
  },
  {
    id: "kling-omni/first-last-frame",
    endpoint: "/kling-video/omni/first-last-frame",
    family: "kling-omni",
    familyName: "Kling Omni",
    workflow: "First last frame",
    description: "First last frame with Kling Omni: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
      {
        name: "last_frame_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "first_frame_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
    ],
  },
  {
    id: "kling-omni/image-reference",
    endpoint: "/kling-video/omni/image-reference",
    family: "kling-omni",
    familyName: "Kling Omni",
    workflow: "Image reference",
    description: "Image reference with Kling Omni: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 10,
      },
      {
        name: "elements",
        type: "array",
        maxItems: 10,
      },
      {
        name: "image_urls",
        type: "array",
        itemFormat: "uri",
        maxItems: 10,
        media: "image",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
    ],
  },
  {
    id: "kling-omni/video-edit",
    endpoint: "/kling-video/omni/video-edit",
    family: "kling-omni",
    familyName: "Kling Omni",
    workflow: "Video edit",
    description: "Video edit with Kling Omni: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "elements",
        type: "array",
        minItems: 0,
        maxItems: 4,
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 4,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "video_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 1,
        itemFormat: "uri",
        media: "video",
      },
    ],
  },
  {
    id: "kling-omni/video-reference",
    endpoint: "/kling-video/omni/video-reference",
    family: "kling-omni",
    familyName: "Kling Omni",
    workflow: "Video reference",
    description: "Video reference with Kling Omni: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "mode",
        type: "string",
        enum: ["std", "pro"],
        default: "pro",
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 3,
        max: 10,
      },
      {
        name: "elements",
        type: "array",
        minItems: 0,
        maxItems: 4,
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 0,
        maxItems: 4,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "video_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 1,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1"],
        default: "16:9",
      },
    ],
  },
  {
    id: "ltx-2-5/image-to-video-fast",
    endpoint: "/lightricks/ltx-2.5/image-to-video/fast",
    family: "ltx-2-5",
    familyName: "LTX-2.5",
    workflow: "Image to video fast",
    description: "Image to video fast with LTX-2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "fps",
        type: "integer",
        enum: [24, 25, 48, 50],
        default: 25,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        required: true,
        enum: [6, 8, 10],
        default: 6,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p", "2k", "4k"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16"],
        default: "16:9",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "camera_movement",
        type: "string",
        enum: ["dolly_in", "dolly_out", "dolly_left", "dolly_right", "jib_up", "jib_down", "static", "focus_shift"],
      },
    ],
  },
  {
    id: "ltx-2-5/image-to-video-pro",
    endpoint: "/lightricks/ltx-2.5/image-to-video/pro",
    family: "ltx-2-5",
    familyName: "LTX-2.5",
    workflow: "Image to video pro",
    description: "Image to video pro with LTX-2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "fps",
        type: "integer",
        enum: [24, 25, 50],
        default: 25,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        required: true,
        enum: [6, 8, 10],
        default: 6,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16"],
        default: "16:9",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "camera_movement",
        type: "string",
        enum: ["dolly_in", "dolly_out", "dolly_left", "dolly_right", "jib_up", "jib_down", "static", "focus_shift"],
      },
    ],
  },
  {
    id: "ltx-2-5/text-to-video-fast",
    endpoint: "/lightricks/ltx-2.5/text-to-video/fast",
    family: "ltx-2-5",
    familyName: "LTX-2.5",
    workflow: "Text to video fast",
    description: "Text to video fast with LTX-2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "fps",
        type: "integer",
        enum: [24, 25, 48, 50],
        default: 25,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        required: true,
        enum: [6, 8, 10],
        default: 6,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p", "2k", "4k"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16"],
        default: "16:9",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "camera_movement",
        type: "string",
        enum: ["dolly_in", "dolly_out", "dolly_left", "dolly_right", "jib_up", "jib_down", "static", "focus_shift"],
      },
    ],
  },
  {
    id: "ltx-2-5/text-to-video-pro",
    endpoint: "/lightricks/ltx-2.5/text-to-video/pro",
    family: "ltx-2-5",
    familyName: "LTX-2.5",
    workflow: "Text to video pro",
    description: "Text to video pro with LTX-2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "fps",
        type: "integer",
        enum: [24, 25, 50],
        default: 25,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        required: true,
        enum: [6, 8, 10],
        default: 6,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16"],
        default: "16:9",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "camera_movement",
        type: "string",
        enum: ["dolly_in", "dolly_out", "dolly_left", "dolly_right", "jib_up", "jib_down", "static", "focus_shift"],
      },
    ],
  },
  {
    id: "minimax-h3/image-to-video",
    endpoint: "/minimax/h3/image-to-video",
    family: "minimax-h3",
    familyName: "MiniMax H3",
    workflow: "Image to video",
    description: "Image to video with MiniMax H3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 5,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["2K"],
        default: "2K",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
        default: "auto",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "aigc_watermark",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "minimax-h3/reference-to-video",
    endpoint: "/minimax/h3/reference-to-video",
    family: "minimax-h3",
    familyName: "MiniMax H3",
    workflow: "Reference to video",
    description: "Reference to video with MiniMax H3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 5,
        max: 15,
      },
      {
        name: "audio_urls",
        type: "array",
        minItems: 0,
        maxItems: 3,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 1,
        maxItems: 9,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["2K"],
        default: "2K",
      },
      {
        name: "video_urls",
        type: "array",
        minItems: 1,
        maxItems: 3,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
        default: "auto",
      },
      {
        name: "aigc_watermark",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "minimax-h3/text-to-video",
    endpoint: "/minimax/h3/text-to-video",
    family: "minimax-h3",
    familyName: "MiniMax H3",
    workflow: "Text to video",
    description: "Text to video with MiniMax H3: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 5,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["2K"],
        default: "2K",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["auto", "adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
        default: "auto",
      },
      {
        name: "aigc_watermark",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "pixverse-v6/image-to-video",
    endpoint: "/pixverse/v6/image-to-video",
    family: "pixverse-v6",
    familyName: "PixVerse V6",
    workflow: "Image to video",
    description: "Image to video with PixVerse V6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "number",
        default: 5,
        min: 1,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["360p", "540p", "720p", "1080p"],
        default: "720p",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "negative_prompt",
        type: "string",
      },
    ],
  },
  {
    id: "pixverse-v6/text-to-video",
    endpoint: "/pixverse/v6/text-to-video",
    family: "pixverse-v6",
    familyName: "PixVerse V6",
    workflow: "Text to video",
    description: "Text to video with PixVerse V6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "number",
        default: 5,
        min: 1,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["360p", "540p", "720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16"],
        default: "16:9",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "negative_prompt",
        type: "string",
      },
    ],
  },
  {
    id: "seedance-2/image-to-video",
    endpoint: "/bytedance/seedance-2.0/image-to-video",
    family: "seedance-2",
    familyName: "Seedance 2.0",
    workflow: "Image to video",
    description: "Image to video with Seedance 2.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 15,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p", "4k"],
        default: "720p",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2/reference-to-video",
    endpoint: "/bytedance/seedance-2.0/reference-to-video",
    family: "seedance-2",
    familyName: "Seedance 2.0",
    workflow: "Reference to video",
    description: "Reference to video with Seedance 2.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 15,
      },
      {
        name: "audio_urls",
        type: "array",
        minItems: 1,
        maxItems: 3,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 1,
        maxItems: 9,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p", "4k"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        minItems: 1,
        maxItems: 3,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
        default: "16:9",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2/text-to-video",
    endpoint: "/bytedance/seedance-2.0/text-to-video",
    family: "seedance-2",
    familyName: "Seedance 2.0",
    workflow: "Text to video",
    description: "Text to video with Seedance 2.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 15,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p", "4k"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
        default: "16:9",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2-5/image-to-video",
    endpoint: "/bytedance/seedance-2.5/image-to-video",
    family: "seedance-2-5",
    familyName: "Seedance 2.5",
    workflow: "Image to video",
    description: "Image to video with Seedance 2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 30,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "bitrate_mode",
        type: "string",
        enum: ["standard", "high"],
        default: "high",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2-5/reference-to-video",
    endpoint: "/bytedance/seedance-2.5/reference-to-video",
    family: "seedance-2-5",
    familyName: "Seedance 2.5",
    workflow: "Reference to video",
    description: "Reference to video with Seedance 2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 30,
      },
      {
        name: "audio_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 1,
        maxItems: 30,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
        default: "16:9",
      },
      {
        name: "bitrate_mode",
        type: "string",
        enum: ["standard", "high"],
        default: "high",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2-5/text-to-video",
    endpoint: "/bytedance/seedance-2.5/text-to-video",
    family: "seedance-2-5",
    familyName: "Seedance 2.5",
    workflow: "Text to video",
    description: "Text to video with Seedance 2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 30,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
        default: "16:9",
      },
      {
        name: "bitrate_mode",
        type: "string",
        enum: ["standard", "high"],
        default: "high",
      },
      {
        name: "output_format",
        type: "string",
        enum: ["mp4", "mov"],
        default: "mp4",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2-5/video-edit",
    endpoint: "/bytedance/seedance-2.5/video-edit",
    family: "seedance-2-5",
    familyName: "Seedance 2.5",
    workflow: "Video edit",
    description: "Video edit with Seedance 2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "audio_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 1,
        maxItems: 30,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "bitrate_mode",
        type: "string",
        enum: ["standard", "high"],
        default: "high",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "seedance-2-5/video-extend",
    endpoint: "/bytedance/seedance-2.5/video-extend",
    family: "seedance-2-5",
    familyName: "Seedance 2.5",
    workflow: "Video extend",
    description: "Video extend with Seedance 2.5: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 4,
        max: 30,
      },
      {
        name: "video_url",
        type: "string",
        required: true,
        format: "uri",
        media: "video",
      },
      {
        name: "audio_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        minItems: 1,
        maxItems: 30,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        minItems: 1,
        maxItems: 10,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "bitrate_mode",
        type: "string",
        enum: ["standard", "high"],
        default: "high",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "wan-2-6/image-to-video",
    endpoint: "/wan/v2.6/image-to-video",
    family: "wan-2-6",
    familyName: "Wan 2.6",
    workflow: "Image to video",
    description: "Image to video with Wan 2.6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: -1,
        max: 10000000,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10, 15],
        default: 5,
      },
      {
        name: "audio_url",
        type: "string",
        format: "uri",
        media: "audio",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "720p",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "wan-2-6/reference-to-video",
    endpoint: "/wan/v2.6/reference-to-video",
    family: "wan-2-6",
    familyName: "Wan 2.6",
    workflow: "Reference to video",
    description: "Reference to video with Wan 2.6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10],
        default: 5,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        required: true,
        minItems: 1,
        maxItems: 3,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1", "4:3", "3:4"],
        default: "16:9",
      },
    ],
  },
  {
    id: "wan-2-6/text-to-video",
    endpoint: "/wan/v2.6/text-to-video",
    family: "wan-2-6",
    familyName: "Wan 2.6",
    workflow: "Text to video",
    description: "Text to video with Wan 2.6: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: -1,
        max: 10000000,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        enum: [5, 10, 15],
        default: 5,
      },
      {
        name: "audio_url",
        type: "string",
        format: "uri",
        media: "audio",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "multi_shots",
        type: "boolean",
        default: false,
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-2-7/image-to-video",
    endpoint: "/wan/v2.7/image-to-video",
    family: "wan-2-7",
    familyName: "Wan 2.7",
    workflow: "Image to video",
    description: "Image to video with Wan 2.7: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "audio_url",
        type: "string",
        format: "uri",
        media: "audio",
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "wan-2-7/reference-to-video",
    endpoint: "/wan/v2.7/reference-to-video",
    family: "wan-2-7",
    familyName: "Wan 2.7",
    workflow: "Reference to video",
    description: "Reference to video with Wan 2.7: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 10,
      },
      {
        name: "image_urls",
        type: "array",
        itemFormat: "uri",
        maxItems: 10,
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "video_urls",
        type: "array",
        itemFormat: "uri",
        maxItems: 10,
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16"],
        default: "16:9",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "wan-2-7/text-to-video",
    endpoint: "/wan/v2.7/text-to-video",
    family: "wan-2-7",
    familyName: "Wan 2.7",
    workflow: "Text to video",
    description: "Text to video with Wan 2.7: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 1,
        max: 2147483646,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 15,
      },
      {
        name: "audio_url",
        type: "string",
        format: "uri",
        media: "audio",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["720p", "1080p"],
        default: "720p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "9:16", "1:1", "4:3", "3:4"],
        default: "16:9",
      },
      {
        name: "prompt_extend",
        type: "boolean",
        default: false,
      },
      {
        name: "negative_prompt",
        type: "string",
        default: "",
      },
    ],
  },
  {
    id: "wan-3/image-to-video",
    endpoint: "/alibaba/wan-3.0/image-to-video",
    family: "wan-3",
    familyName: "Wan 3.0",
    workflow: "Image to video",
    description: "Image to video with Wan 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-3/reference-to-video",
    endpoint: "/alibaba/wan-3.0/reference-to-video",
    family: "wan-3",
    familyName: "Wan 3.0",
    workflow: "Reference to video",
    description: "Reference to video with Wan 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "file_url",
        type: "string",
        format: "uri",
      },
      {
        name: "link_url",
        type: "string",
        format: "uri",
      },
      {
        name: "audio_urls",
        type: "array",
        maxItems: 5,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        maxItems: 10,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "video_urls",
        type: "array",
        maxItems: 5,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-3/text-to-video",
    endpoint: "/alibaba/wan-3.0/text-to-video",
    family: "wan-3",
    familyName: "Wan 3.0",
    workflow: "Text to video",
    description: "Text to video with Wan 3.0: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-3-prime/image-to-video",
    endpoint: "/alibaba/wan-3.0-prime/image-to-video",
    family: "wan-3-prime",
    familyName: "Wan 3.0 Prime",
    workflow: "Image to video",
    description: "Image to video with Wan 3.0 Prime: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "image_url",
        type: "string",
        required: true,
        format: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "end_image_url",
        type: "string",
        format: "uri",
        media: "image",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-3-prime/reference-to-video",
    endpoint: "/alibaba/wan-3.0-prime/reference-to-video",
    family: "wan-3-prime",
    familyName: "Wan 3.0 Prime",
    workflow: "Reference to video",
    description: "Reference to video with Wan 3.0 Prime: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "file_url",
        type: "string",
        format: "uri",
      },
      {
        name: "link_url",
        type: "string",
        format: "uri",
      },
      {
        name: "audio_urls",
        type: "array",
        maxItems: 5,
        itemFormat: "uri",
        media: "audio",
      },
      {
        name: "image_urls",
        type: "array",
        maxItems: 10,
        itemFormat: "uri",
        media: "image",
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "video_urls",
        type: "array",
        maxItems: 5,
        itemFormat: "uri",
        media: "video",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "wan-3-prime/text-to-video",
    endpoint: "/alibaba/wan-3.0-prime/text-to-video",
    family: "wan-3-prime",
    familyName: "Wan 3.0 Prime",
    workflow: "Text to video",
    description: "Text to video with Wan 3.0 Prime: request parameters, examples and response handling.",
    output: "video",
    fields: [
      {
        name: "seed",
        type: "integer",
        min: 0,
        max: 2147483647,
      },
      {
        name: "prompt",
        type: "string",
        required: true,
      },
      {
        name: "duration",
        type: "integer",
        default: 5,
        min: 2,
        max: 30,
      },
      {
        name: "resolution",
        type: "string",
        enum: ["480p", "720p", "1080p"],
        default: "1080p",
      },
      {
        name: "aspect_ratio",
        type: "string",
        enum: ["16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
        default: "adaptive",
      },
      {
        name: "generate_audio",
        type: "boolean",
        default: true,
      },
      {
        name: "enable_thinking",
        type: "boolean",
        default: false,
      },
    ],
  },
]
